import axios from 'axios'
const api = axios.create({ baseURL: '/api', timeout: 15000 })
api.interceptors.request.use(c => { const t = localStorage.getItem('admin_token'); if(t) c.headers.Authorization=`Bearer ${t}`; return c })
api.interceptors.response.use(r => r, e => { if(e.response?.status===401){ localStorage.clear(); window.location.href='/login' } return Promise.reject(e) })
export default api
export const login = (d) => api.post('/auth/login', d)
export const getMe = () => api.get('/auth/me')
export const getUser = (id) => api.get(`/users/${id}`)
export const adminDashboard = () => api.get('/admin/dashboard')
export const adminListUsers = (p) => api.get('/admin/users', { params: p })
export const adminCreateUser = (d) => api.post('/admin/users', d)
export const adminUpdateUser = (id, d) => api.put(`/admin/users/${id}`, d)
export const adminToggleStatus = (id, d) => api.put(`/admin/users/${id}/status`, d)
export const adminRemoveVip = (id) => api.post(`/admin/users/${id}/remove-vip`)
export const adminDeleteUser = (id) => api.delete(`/admin/users/${id}`)
export const adminWarnUser = (id, d) => api.post(`/admin/users/${id}/warn`, d)
export const adminUserWarnings = (id) => api.get(`/admin/users/${id}/warnings`)
export const adminReviewQueue = (p) => api.get('/admin/review-queue', { params: p })
export const adminApprove = (id) => api.post(`/admin/review-queue/${id}/approve`)
export const adminReject = (id, d) => api.post(`/admin/review-queue/${id}/reject`, d)
export const adminBatchReview = (d) => api.post('/admin/review-queue/batch', d)
export const adminBatchDelete = (d) => api.post('/admin/review-queue/batch-delete', d)
export const adminGenerateCards = (d) => api.post('/admin/cards/generate', d)
export const adminListBatches = () => api.get('/admin/cards/batches')
export const adminBatchDetail = (id, p) => api.get(`/admin/cards/batches/${id}`, { params: p })
export const adminDeleteCard = (id) => api.delete(`/admin/cards/${id}`)
export const adminExportBatch = (id) => api.get(`/admin/cards/batches/${id}/export`)
export const adminChats = () => api.get('/admin/chats')
export const adminChatMsgs = (id) => api.get(`/admin/chats/${id}/messages`)
export const adminReports = (p) => api.get('/admin/reports', { params: p })
export const adminHandleReport = (id, d) => api.post(`/admin/reports/${id}/handle`, d)
export const adminSiteConfigs = () => api.get('/admin/site-configs')
export const adminUpdateConfig = (key, d) => api.put(`/admin/site-configs/${key}`, d)
export const adminImageUrl = (p) => { const t = localStorage.getItem('admin_token')||''; return `/api/admin/image-preview?path=${encodeURIComponent(p)}&token=${t}` }
